### ISSUE TITLE
Question about cycle_capacity

### ISSUE THREAD

**Issue by mschwartz** [natekspencer/pylitterbot#105]
What does it mean? :)

Digging into the source, it is a number with default of 30.  You seem to understand that 30 is a good default, assuming it's not able to be gotten from the robot/api...

**Comment by mschwartz** [comment]
Also, thanks for this!

**Comment by natekspencer** [comment]
This indicates the number of anticipated clean cycles that can be performed before the robot waste drawer is full 

I want to say when I was initially working on this and only the LR3 existed, that when you reset the waste drawer it would send the value 30 for cycle capacity if it didn't have one and that's where I grabbed the number from. That and a combination of my own robot usually hovering around that number, so it felt ok to use.

**Comment by mschwartz** [comment]
Thanks!  Maybe document this in comments in the code?

Almost everything else makes sense to me.

again, thanks for this!

**Comment by natekspencer** [comment]
Added clarity in 2023.1.2
