### ISSUE TITLE
Unable to connect to API

### ISSUE THREAD

**Issue by STiCory** [natekspencer/pylitterbot#12]
Hi, tried adding the integration and I am getting two errors:
`2022-01-02 15:53:13 ERROR (MainThread) [homeassistant.components.litterrobot.hub] Unable to connect to Litter-Robot API`
And
`2022-01-02 15:53:13 ERROR (MainThread) [homeassistant.components.litterrobot.hub] Unable to connect to Litter-Robot API
2022-01-02 15:53:13 WARNING (MainThread) [homeassistant.config_entries] Config entry 'redacted' for litterrobot integration not ready yet: Unable to connect to the Litter-Robot API.; Retrying in background`

Running:
home Assistant; core-2021.8.1
Python; 3.8.12

PS, reading through what you have done here creating the API and then the custom integration and eventually getting it incorporated with core is incredible.

**Comment by STiCory** [comment]
Going on 36 hours of the integration retrying a connection to the API every ~1 minute and still not working. I've tried disabling and re-enabling the integration as well as restarting home assistant altogether multiple times to no avail either.

Am I doing something wrong?

**Comment by natekspencer** [comment]
It looks like your instance of Home Assistant is 4 months behind. There have been some changes, including one with the August release of Home Assistant that required a bump of the underlying auth library that had some breaking changes. HA release 2021.8.2 pulled the change for this in, so you'll need at least that version.

https://www.home-assistant.io/blog/posts/2#release-202182---august-5

**Comment by STiCory** [comment]
OMG I never replied to this! Sorry!!!
I updated and everything is working fine! For what it's worth, I'm current at 2022.2.2 now and it's working like a dream, I made some conditional cards that change what's displayed in case it's off/ cleaning/ "idle" and then a button that I press and hold to reset the waste drawer (so that I don't just accidentally tap it and reset it)
One of my favorite integrations honestly haha
![image](https://user-images.githubusercontent.com/10111499/152839845-416a3e0e-e69e-4523-9359-5bf2a1f93772.png)
