### ISSUE TITLE
Login fails when password contains a non-ASCII character

### ISSUE THREAD

**Issue by risteristevski** [natekspencer/pylitterbot#15]
I was trying to set-up the Home Assistant Litter-Robot integration when I was unable to log in to my litter-robot account.
Digging through the logs I found out that the issue stems from this library.

The error I got is the following:
UnicodeEncodeError: 'ascii' codec can't encode character '\xa3' in position 15: ordinal not in range(128) 

A work-around was to remove the pound symbol (£) from my password.

**Comment by natekspencer** [comment]
2022.8.0b0 should fix this as well as add support for the Litter-Robot 4
https://github.com/home-assistant/core/pull/75790

**Comment by natekspencer** [comment]
Resolved in 2022.8.0
