### ISSUE TITLE
Question: Is there any way to emulate pressing the "Cycle" button?

### ISSUE THREAD

**Issue by mkanet** [natekspencer/pylitterbot#154]
I have a feeling the API doesn't support executing the "Cycle" command for the Litter-Robot 3 or Litter-Robot 4.  However, I'm curious if there's any unofficial/undocumented method to do this.  It would be a very useful feature.

**Comment by natekspencer** [comment]
You can start a clean cycle from this already.

**Comment by mkanet** [comment]
> You can start a clean cycle from this already.
Thanks.  Somehow I had missed `await robot.start_cleaning()`
