### ISSUE TITLE
Reset Waste Drawer No Longer Works?

### ISSUE THREAD

**Issue by russgould** [natekspencer/pylitterbot#171]
Due to a faulty sensors in my LR3, I was using the reset_waste_drawer() method to periodically force the robot to think the waste drawer had been emptied so it would continue to cycle. I just updated to v2023.4.6 and while that solved the error the script was throwing about the deprecated user api, I just saw the reset_waste_drawer() method is no longer mentioned in the readme and doesn't appear to be functioning although its not throwing any errors. It also seems to not work from the Whisker app now either. Not sure if the issue is on my end or they changed the API again? Is it no longer possible to reset the waste drawer from the API or something? Also thank you for your efforts on this. Glad to see you're still updating it as it is super useful.

**Comment by natekspencer** [comment]
If it no longer functions via the Whisker app, it's probably been deprecated on their side. I no longer operate an LR3, so I wouldn't be able to test it either unfortunately

**Comment by natekspencer** [comment]
It still shows up in the app though, so it could just be related to ongoing changes they are doing at the moment
