### ISSUE TITLE
Is it possible to pull pets in and their weight?

### ISSUE THREAD

**Issue by flyize** [natekspencer/pylitterbot#190]
The LR4 added pets and weight. Is it possible to poll that data too? I'd love to track my fat cats weight in Home Assistant!

**Comment by natekspencer** [comment]
I haven't had a chance to try and find what endpoints are used to query that information yet with all the other projects I am involved in. Since it is in the app, it's definitely there somewhere, but low on my priority list at the moment.

**Comment by jrhe** [comment]
I have the data needed for this and should be able to put in a PR shortly.

**Comment by tjhorner** [comment]
@jrhe were you able to make any progress on this? Any notes you are able to share would be great

**Comment by natekspencer** [comment]
This is now available in v2023.5.0. I'll work on getting pets in Home Assistant next

**Comment by tjhorner** [comment]
Thanks @natekspencer!

**Comment by natekspencer** [comment]
@flyize I have not had time to add it to Home Assistant yet.

**Comment by flyize** [comment]
No worries! I can pull pet weight with pylitterrobot tho? Maybe I can figure out how to pull manually and add to HA.

**Comment by ShagoY** [comment]
> No worries! I can pull pet weight with pylitterrobot tho? Maybe I can figure out how to pull manually and add to HA.

Hello, did you manage to retrieve the cat profiles in HA?
