### ISSUE TITLE
Issue for sample.py

### ISSUE THREAD

**Issue by gpeng1216** [natekspencer/pylitterbot#191]
Hi 
I was able to pull the code and updated username and password in sample.py but there's either no data available for the account . Would you mind checking for this issue? Thank you

DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:pylitterbot.session:Making POST request to https://42nk7qrhdg.execute-api.us-east-1.amazonaws.com/prod/login
DEBUG:pylitterbot.session:Received 200 response from https://42nk7qrhdg.execute-api.us-east-1.amazonaws.com/prod/login: {'token': '**REDACTED**'}
DEBUG:pylitterbot.session:Making POST request to https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyCustomToken
DEBUG:pylitterbot.session:Received 200 response from https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyCustomToken: {'kind': 'identitytoolkit#VerifyCustomTokenResponse', 'idToken': '**REDACTED**', 'refreshToken': '**REDACTED**', 'expiresIn': '3600', 'isNewUser': False}
DEBUG:pylitterbot.session:Making GET request to https://v2.api.whisker.iothings.site/users/1144947/robots
DEBUG:pylitterbot.session:Making POST request to https://lr4.iothings.site/graphql
DEBUG:pylitterbot.session:Making POST request to https://graphql.whisker.iothings.site/v1/graphql
DEBUG:pylitterbot.session:Received 200 response from https://v2.api.whisker.iothings.site/users/1144947/robots: []
DEBUG:pylitterbot.session:Received 200 response from https://graphql.whisker.iothings.site/v1/graphql: {'data': {'feeder_unit': []}}

**Comment by natekspencer** [comment]
I'm not sure I see an issue with this at the moment. There's no errors here, but I don't see any robots being returned. Have you added a robot to your account already?

**Comment by gpeng1216** [comment]
Yes the account info works with Whisker App on my phone. Is there any step for adding robots to my account?
