### ISSUE TITLE
[RFE] Status/Litter/Waste

### ISSUE THREAD

**Issue by slapcat** [natekspencer/pylitterbot#202]
The most useful stats from the litter robot for me are the current status, litter health, and waste level. Unfortunately it doesn't seem like this is captured in the current data from `get_activity_history()` or `get_insight()`. Would it be possible to add a method to capture this?

**Comment by natekspencer** [comment]
You can get those from the appropriate properties of the robot: `status`, `litter_level`, and `waste_drawer_level`. That information, however, is not available for historical commands so you'd have to keep your own history if you want to track that.
