### ISSUE TITLE
Question About Subscribe

### ISSUE THREAD

**Issue by jamespauly** [natekspencer/pylitterbot#227]
Do you have any example of how to use the account.load_robots(True).  Where you are subscribing to get the updates for the robots?  Just curious on how to utilize that receiver.

Thanks,
James

**Comment by natekspencer** [comment]
The robots have an event emitter, so you can subscribe to those via something like:

```python
from pylitterbot.robot import EVENT_UPDATE
...
robot = account.robots[0]
robot.on(EVENT_UPDATE, <some_callback>)
```

The Home-Assistant code uses this library so you can peruse through that on how it can be used as well https://github.com/home-assistant/core/tree/dev/homeassistant/components/litterrobot

**Comment by jamespauly** [comment]
Okay that makes sense I see it in the HA code.  I’m trying to get this to work on the EISY on a node plugin.

Thanks much
