### ISSUE TITLE
Feature Request Litter Robot 4

### ISSUE THREAD

**Issue by jwelvaert** [natekspencer/pylitterbot#258]
Can you add the ability to activate the Clean Cycle via HA? My Litter Robot 4 used to activate Clean Cycle every time the power was cycled but that evidently changed in a recent firmware update. Occasionally my robot would error and power cycling would usually clear that so I made an automation to power cycle when the error didn't clear after so many minutes. Activating the Clean Cycle can be done through the Whisker app but I want to automate it through HA. Thanks for your work on this integration.

**Comment by natekspencer** [comment]
This can already be done with the vacuum entity in HA. Just call vacuum.start or initiate it through the vacuum entity.

**Comment by jwelvaert** [comment]
Thanks. I was looking for a switch. I never think of the robot as a vacuum. LOL
