### ISSUE TITLE
unable to close connection

### ISSUE THREAD

**Issue by Broenink** [natekspencer/pylitterbot#8]
Thanks for your work!

I'm using pylitterbot on raspbian container for some time, and it worked great! Today I moved it to a debian:buster container. The script is still working, however when running sample.py, I get the following warning:

``` bash
homeserver:/scripts# python3 ./sample.py
Robots:
Name: ***********, Serial: *********, id: ***********
/usr/local/lib/python3.7/dist-packages/httpx/_client.py:2004: UserWarning: Unclosed <authlib.integrations.httpx_client.oauth2_client.AsyncOAuth2Client object at 0xb5b3d290>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
  f"Unclosed {self!r}. "
```

So the connection is not correctly closed, and I also don't see how I could close it properly.

**Comment by natekspencer** [comment]
What version of pylitterbot and which version of httpx do you have installed?

**Comment by Broenink** [comment]
httpx  version 0.19.0, and pylitterbot version 2021.8.1

**Comment by natekspencer** [comment]
I'll have to update the sample, but all you should need to do is call `account.disconnect()` when finished with it.

**Comment by Broenink** [comment]
Thanks.
I tried adding the disconnect request. Unfortunatly, the disconnect function does not exist in the account class, as a result I got the following error:

```bash
homeserver:/scripts# python3 ./sample.py
Robots:
Name: **********, Serial: **********, id: *************
Traceback (most recent call last):
  File "./sample.py", line 24, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./sample.py", line 21, in main
    account.disconnect()
AttributeError: 'Account' object has no attribute 'disconnect'
/usr/local/lib/python3.7/dist-packages/httpx/_client.py:2004: UserWarning: Unclosed <authlib.integrations.httpx_client.oauth2_client.AsyncOAuth2Client object at 0xb5acaed0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
```

**Comment by natekspencer** [comment]
Yeah I think I told you incorrectly. 🤦🏻‍♂️ I'm trying to do it from memory, but I mistook what I implemented in another one of my python projects for what this one had. I'll take a look once I get back to a computer this week!

**Comment by Broenink** [comment]
Thanks in advance!

**Comment by Broenink** [comment]
Thanks!
